
# -------------------------- BASE --------------------------
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim as base

WORKDIR /app

EXPOSE 80
EXPOSE 443


# -------------------------- BUILD --------------------------
FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch as build

WORKDIR /src
RUN mkdir -p /src/Services
RUN mkdir -p /src/Events

COPY appscore/Foundation/Events Events/
COPY appscore/Services/ Services/

RUN dotnet restore Services/Applicants.Api/applicants.api.csproj
#NOTES: identity.Api.csproj with capital A and I
RUN dotnet restore Services/Identity.Api/Identity.Api.csproj
RUN dotnet restore Services/Jobs.Api/jobs.api.csproj

RUN dotnet restore Events/Events.csproj

# COPY . .

RUN mkdir -p /app/build

WORKDIR /Services/Applicants.Api/
RUN dotnet build "applicants.api.csproj" -c Release -o /app/build

# WORKDIR /src/Services/Identity.Api
# RUN dotnet build Identity.Api.csproj -c Release -o /app/build

# WORKDIR /src/Services/Jobs.Api
# RUN dotnet build jobs.api.csproj -c Release -o /app/build

# WORKDIR /src/Events
# RUN dotnet build Events.csproj -c Release -o /app/build

# # -------------------------- PUBLISH --------------------------
# FROM build as publish

# WORKDIR /src/Services/Applicants.Api
# RUN dotnet publish applicants.api.csproj -c Release -o /app/publish

# WORKDIR /src/Services/Identity.Api
# RUN dotnet publish Identity.Api.csproj -c Release -o /app/publish

# WORKDIR /src/Services/Jobs.Api
# RUN dotnet publish jobs.api.csproj -c Release -o /app/publish

# WORKDIR /src/Events
# RUN dotnet publish Events.csproj -c Release -o /app/publish

# # -------------------------- FINAL --------------------------
# FROM base as final

# WORKDIR /app
# COPY --from=publish /app/publish .

# Exécuter le entrypoint suivant: ["dotnet", "{nom_du_projet.dll}"]
# ENTRYPOINT [ "dotnet" ]

